### ISSUE TITLE
browser.sessionId undefined Error in nightwatch 2.0.10

### ISSUE THREAD

**Issue by petamoriken** [reallymello/nightwatch-saucelabs-endsauce#3]
I tried updating nightwatch-saucelabs-endsauce, but apparently it doesn't work because `this.api.sessionId` is always `undefined`. See https://github.com/petamoriken/float16/pull/661 if you want.

**Comment by reallymello** [comment]
In the new version .endSauce() needs to be called before you close your browser because once the browser is closed this.api.sessionId clears. 

In your example, you appear to be calling browser.close() _before_ browser.endSauce().

Example repository https://github.com/reallymello/nightwatchTutorials/blob/master/sauceLabsExample/

I'll check to see if there is a fallback place to get the sessionId from so that it is less sensitive to the order it was being called, but I noticed where I was getting the remote session id from before was unavailable in Nightwatch 2.0+ which is why the change was made.

**Comment by reallymello** [comment]
I updated the documentation to make it more clear about the order change and added a fallback for older Nightwatch versions where you could access the session id from the capabilities collection from a key called `['webdriver.remote.sessionid']`

Let me know if calling it before the browser is closed is acceptable in your test-flow. If it isn't I may be able to come up with a more complicated fallback.

**Comment by petamoriken** [comment]
> In the new version .endSauce() needs to be called before you close your browser because once the browser is closed this.api.sessionId clears.

Thanks for the explanation. I confirmed it worked fine with that.

> I updated the documentation to make it more clear about the order change and added a fallback for older Nightwatch versions where you could access the session id from the capabilities collection from a key called `['webdriver.remote.sessionid']`

nice work 👍
